Fix remaining issues in applications and demos from the updated spaceros base image
space-ros/docker pull request #189
Opened 2024-09-19 13:06 UTC by eholum

Resolves #161

2024-09-24 11:38 UTC, asimonov commented
I am trying to test #152, but that requires moveit2 docker which is failing on `main`.

shall we test/push this one first to make life easier?

2024-09-25 06:56 UTC, asimonov commented
yes, I am using the locally built images. but it is getting confusing...

basically if our ultimate test is to run moveit and rover demos that requires all the images to 1. be built, 2. be consistent. and they require different PRs to be brought to that state.

if we could save branch tagged images and start merging PRs, that would alleviate confusion to some degree

2024-09-27 13:11 UTC, eholum commented
> yes, I am using the locally built images. but it is getting confusing...

Ugh, yes sorry things have been in an odd state, but now that the main image is updated and pushed to Dockerhub, too things should be more clear? This PR should resolve the build issues on `main`, and also open things up to using different base images for the moveit and nav2 builds.

2024-09-27 17:30 UTC, asimonov commented
> > yes, I am using the locally built images. but it is getting confusing...
> 
> Ugh, yes sorry things have been in an odd state, but now that the main image is updated and pushed to Dockerhub, too things should be more clear? This PR should resolve the build issues on `main`, and also open things up to using different base images for the moveit and nav2 builds.

almost... git-lfs change on simulation broke my local build of docker/space_robots... https://github.com/space-ros/simulation/issues/35

i think we need to test every PR on affected repos by running those 2 demos. because they effectively combine everything we have

2024-09-27 17:31 UTC, asimonov commented
Erik, can you include the lfs setup into this PR as well?

2024-09-29 23:30 UTC, eholum commented
> Erik, can you include the lfs setup into this PR as well?

Ugh, in the interest of traceability I included that fix in https://github.com/space-ros/docker/pull/194, since that was broken by a separate change... 

> i think we need to test every PR on affected repos by running those 2 demos. because they effectively combine everything we have

This is a big ask until we get some sort of automated infrastructure in place to at least pre-build those images. Or in an ideal worth a pre-build and a basic sanity check. But hopefully we can get that done sooner rather than later?

2024-10-01 10:20 UTC, asimonov approved these changes
looks good. and it builds locally.

but i cannot test demos (mars rover and navigation) because of other issues (e.g. https://github.com/space-ros/docker/pull/194)

i suggest we merge all these PRs releated to fixing the build and then re-test the demos

2024-10-01 15:49 UTC, EzraBrooks requested changes
Can we break out the GitHub Actions version bumps into another issue/PR? Everything else is clearly related

2024-10-01 17:03 UTC, eholum commented
> Can we break out the GitHub Actions version bumps into another issue/PR? Everything else is clearly related

Done. Squashed those changes out of the param change commits and updated. Everything else remains unchanged. I'll open a separate issue to update CI since there's more that would be helpful now that we have main available...

2024-10-01 18:39 UTC, EzraBrooks approved these changes
These code changes all make obvious sense to me.

2024-10-01 18:42 UTC, merged

2024-10-01 18:42 UTC, eholum commented
> i suggest we merge all these PRs releated to fixing the build and then re-test the demos

The time is nigh!